/**
 * autogenerated code
 * @author Kholod, Serhii
 */

sap.ui.define("app/Component", ["sap/ui/core/UIComponent"], function (UIComponent) {
  "use strict";

  return UIComponent.extend("app.Component", {
    
    metadata: {
      manifest: "json",
      manifestFirst: true
    },
    
    init: function init() {
      UIComponent.prototype.init.apply(this, [arguments]);
    },
    
    onBeforeRendering: function onBeforeRendering() {
      
      this.setModel(new sap.ui.model.json.JSONModel({
        value: "ValueForComponentCustomProperty"
      }));
    }
  });
});
